version: "3"
services:
  core:
    build:
      context: ./docker
      dockerfile: Dockerfile-dev
    image: mediastrends-core-dev:0.1.0
    container_name: mediastrends-core-dev
    user: root
    volumes:
      - "${PWD}:/app"
      - "${PWD}/data:/data"
      - "${PWD}/sqlite/:/sqlite"
    labels:
      - "traefik.enable=true"
      - "traefik.port=8888"
    env_file:
      - .env
    networks:
      - default
      - netproxy

  sqliteweb:
    image: coleifer/sqlite-web
    volumes:
      - "${PWD}/sqlite:/data"
    labels:
      - "traefik.enable=true"
      - "traefik.port=8080"
      - "traefik.main.frontend.entryPoints=http"
    environment:
      - SQLITE_DATABASE=database_dev.db

  airflow:
    image: puckel/docker-airflow
    command: webserver
    labels:
      - "traefik.enable=true"
      - "traefik.port=8080"
      - "traefik.main.frontend.entryPoints=http"
    ports:
      - 127.0.0.1:18080:8080
    networks:
     - default
     - netproxy

  jackett:
    image: linuxserver/jackett
    container_name: mediastrends-jackett-dev
    env_file:
      - .env
    volumes:
      - ${PWD}/jackett/config:/config
      - ${PWD}/jackett/downloads:/downloads
    labels:
      - "traefik.enable=true"
      - "traefik.port=9117"
      - "traefik.main.frontend.entryPoints=http"
    ports:
      - 127.0.0.1:19117:9117
    networks:
      - default
      - netproxy

networks:
  netproxy:
    external:
      name: netproxy