version: "3"
services:
  core-prod:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        USER_UID: 1000
    image: mediastrends-core-prod:1.0.0
    container_name: mediastrends-core-prod
    user: mediastrends
    depends_on:
      - jackett-prod
    volumes:
      - "${PWD}/config/mediastrends.prod.ini:/app/mediastrends.prod.ini"
      - "${PWD}/sqlite/:/app/sqlite"
      - "${PWD}/config/indexers.yaml:/app/config/indexers.yaml"
      - "${PWD}/config/trackers.yaml:/app/config/trackers.yaml"
    environment:
      - TZ=Europe/Paris
      - MEDIASTRENDS_MODE=prod

  jackett-prod:
    image: linuxserver/jackett:latest
    container_name: mediastrends-jackett-prod
    environment:
      - "TZ=Europe/Paris"
    volumes:
      - ${PWD}/jackett/config:/config
      - ${PWD}/jackett/downloads:/downloads
    labels:
      - "traefik.enable=true"
      - "traefik.port=9117"
      - "traefik.main.frontend.entryPoints=http"
    ports:
      - 127.0.0.1:29117:9117
