ARG BASE_CONTAINER=python:3.7-buster
FROM $BASE_CONTAINER

ARG USERNAME=vscode
ARG USER_UID=1001
ARG USER_GID=$USER_UID
ARG WORKDIR=/package

WORKDIR $WORKDIR
ENV WORKDIR=$WORKDIR

# use prod package version
RUN DEBIAN_FRONTEND=noninteractive apt-get update && \
	apt-get install --no-install-recommends --yes python3-pandas \
    python3-scipy python3-sklearn python3-sqlalchemy \
    python3-lxml python3-multidict python3-yarl && \
	rm -rf /var/lib/apt/lists/*

ENV PYTHONPATH=$PYTHONPATH:/usr/lib/python3/dist-packages

# Create the user
RUN groupadd --gid $USER_GID $USERNAME \
    && useradd --uid $USER_UID --gid $USER_GID -m $USERNAME \
    && chown -R $USER_UID:$USER_GID $WORKDIR

USER $USERNAME

ENV PATH="~/.local/bin:${PATH}"

COPY requirements.txt .
RUN pip install --no-warn-script-location -r requirements.txt

USER root

# use entrypoint one day
CMD ["tail", "-f", "/dev/null"]
